//
// Created by liuzikai on 2019-01-30.
//

#ifndef META_INFANTRY_VEHICLE_ENGINEER_H
#define META_INFANTRY_VEHICLE_ENGINEER_H

/** Mechanism Parameters */
#define CHASSIS_WHEEL_BASE  600.0f  // distance between front axle and the back axle, mm
#define CHASSIS_WHEEL_TREAD 560.0f  // distance between left and right wheels, mm
#define CHASSIS_WHEEL_CIRCUMFERENCE 478.0f  // mm

#define ENGINEER_CHASSIS_VELOCITY_MAX 10.0f
#define ENGINEER_CHASSIS_W_MAX 10.0f
#define ENGINEER_AIDED_MOTOR_VELOCITY 600.0f
#define ANGLE_HEIGHT_RATIO 458.0f  // [degree/cm]

#define ROBOTIC_ARM_STRETCH_OUT_ANGLE 120.0f
#define ROBOTIC_ARM_PULL_BACK_ANGLE 30.0f
#define ROBOTIC_ARM_ROTATE_VELOCITY 50.0f
#define ROBOTIC_ARM_TRIGGER_VELOCITY 5.0f

/*** Chassis PID Params ***/

#define CHASSIS_PID_V2I_KP 33.0f
#define CHASSIS_PID_V2I_KI 0.49f
#define CHASSIS_PID_V2I_KD 2.4f
#define CHASSIS_PID_V2I_I_LIMIT 4000.0f
#define CHASSIS_PID_V2I_OUT_LIMIT 5000.0f
#define CHASSIS_PID_V2I_PARAMS \
    {CHASSIS_PID_V2I_KP, CHASSIS_PID_V2I_KI, CHASSIS_PID_V2I_KD, \
    CHASSIS_PID_V2I_I_LIMIT, CHASSIS_PID_V2I_OUT_LIMIT}

#define ELEVATOR_PID_A2V_KP 3.0f
#define ELEVATOR_PID_A2V_KI 0.0f
#define ELEVATOR_PID_A2V_KD 0.0f
#define ELEVATOR_PID_A2V_V_LIMIT 2000.0f
#define ELEVATOR_PID_A2V_OUT_LIMIT 3000.0f
#define ELEVATOR_PID_A2V_PARAMS \
    {ELEVATOR_PID_A2V_KP, ELEVATOR_PID_A2V_KI, ELEVATOR_PID_A2V_KD, \
    ELEVATOR_PID_A2V_V_LIMIT, ELEVATOR_PID_A2V_OUT_LIMIT}

#define ELEVATOR_PID_V2I_KP 1.5f
#define ELEVATOR_PID_V2I_KI 0.022f
#define ELEVATOR_PID_V2I_KD 0.0f
#define ELEVATOR_PID_V2I_I_LIMIT 4000.0f
#define ELEVATOR_PID_V2I_OUT_LIMIT 5000.0f
#define ELEVATOR_PID_V2I_PARAMS \
    {ELEVATOR_PID_V2I_KP, ELEVATOR_PID_V2I_KI, ELEVATOR_PID_V2I_KD, \
    ELEVATOR_PID_V2I_I_LIMIT, ELEVATOR_PID_V2I_OUT_LIMIT}

#define AIDED_MOTOR_PID_V2I_KP 15.0f
#define AIDED_MOTOR_PID_V2I_KI 0.22f
#define AIDED_MOTOR_PID_V2I_KD 0.0f
#define AIDED_MOTOR_PID_V2I_I_LIMIT 4000.0f
#define AIDED_MOTOR_PID_V2I_OUT_LIMIT 5000.0f
#define AIDED_MOTOR_PID_V2I_PARAMS \
    {AIDED_MOTOR_PID_V2I_KP, AIDED_MOTOR_PID_V2I_KI, AIDED_MOTOR_PID_V2I_KD, \
    AIDED_MOTOR_PID_V2I_I_LIMIT, AIDED_MOTOR_PID_V2I_OUT_LIMIT}

#endif //META_INFANTRY_VEHICLE_ENGINEER_H
