//
// Created by liuzikai on 2019-01-28.
//

#ifndef META_INFANTRY_MAIN_INFANTRY_ONE_H
#define META_INFANTRY_MAIN_INFANTRY_ONE_H

#define VEHICLE_INFANTRY  // define the common macro for all infantry

#define GIMBAL_PID_YAW_V2I_KP 5.1f
#define GIMBAL_PID_YAW_V2I_KI 0.075f
#define GIMBAL_PID_YAW_V2I_KD 0.021f
#define GIMBAL_PID_YAW_V2I_I_LIMIT 1000.0f
#define GIMBAL_PID_YAW_V2I_OUT_LIMIT 3000.0f

#define GIMBAL_PID_YAW_A2V_KP 4.9f
#define GIMBAL_PID_YAW_A2V_KI 0.0f
#define GIMBAL_PID_YAW_A2V_KD 2.0f
#define GIMBAL_PID_YAW_A2V_I_LIMIT 1000.0f
#define GIMBAL_PID_YAW_A2V_OUT_LIMIT 3000.0f

#define GIMBAL_PID_PITCH_V2I_KP 5.55f
#define GIMBAL_PID_PITCH_V2I_KI 0.22f
#define GIMBAL_PID_PITCH_V2I_KD 0.0165f
#define GIMBAL_PID_PITCH_V2I_I_LIMIT 1000.0f
#define GIMBAL_PID_PITCH_V2I_OUT_LIMIT 3000.0f

#define GIMBAL_PID_PITCH_A2V_KP 5.75f
#define GIMBAL_PID_PITCH_A2V_KI 0.0f
#define GIMBAL_PID_PITCH_A2V_KD 0.55f
#define GIMBAL_PID_PITCH_A2V_I_LIMIT 1000.0f
#define GIMBAL_PID_PITCH_A2V_OUT_LIMIT 3000.0f

#define GIMBAL_YAW_ACTUAL_VELOCITY (-MPU6500Controller::angle_speed.x)
#define GIMBAL_PITCH_ACTUAL_VELOCITY (-MPU6500Controller::angle_speed.y)


#endif //META_INFANTRY_MAIN_INFANTRY_ONE_H
